ALTER TABLE receitas ADD COLUMN usuario_id BIGINT NOT NULL;
ALTER TABLE receitas ADD CONSTRAINT RECEITAS_FK_USUARIO FOREIGN KEY(usuario_id) REFERENCES usuarios(id);

ALTER TABLE despesas ADD COLUMN usuario_id BIGINT NOT NULL;
ALTER TABLE despesas ADD CONSTRAINT DESPESAS_FK_USUARIO FOREIGN KEY(usuario_id) REFERENCES usuarios(id);
